### ISSUE TITLE
TypeError file.map error when attempting to create folder in Cartridge directory

### ISSUE THREAD

**Issue by jgamb** [mzwallace/dw-cli#24]
We recently attempted to upload our source code to SFCC staging and got an error in our bitbucket pipeline ex. “✖ Creating remote folder /Cartridges/version10”. 
```
[13:40:15] Pushing version10 to …..
- 
✔ Zipping 'cartridges'
- Zipping 'cartridges'
✖ Creating remote folder /Cartridges/version10
[13:40:19] Error 4.228s
```

After doing some digging around we found we needed to update from 2.2.0 -> 3.0.3.
However, after updating to 3.0.3 and re-running the bitbucket pipeline we’re now getting the error in the command "dw push" below ex. “TypeError: files.map is not a function”
node:14.16.0
dw-cli@3.0.3
```	
[12:51:50] Pushing version21 to …. 
✔ Zipping 'cartridges'
- Zipping 'cartridges'
✔ Creating remote folder Cartridges/version21
- Creating remote folder Cartridges/version21
✖ Cleaning remote folder Cartridges/version21
[12:51:54] TypeError: files.map is not a function 4.543s
```

**Comment by jgamb** [comment]
It was an Authentication issue. This is is closed
